name: manual performing Individual task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - 'upgrade-package'
          - 'spawn-container'
          - 'delete-container'
          - 'scan-images'
          - 'push-images'

jobs:
  upgrade-package:
    if: github.event.inputs.environment == 'upgrade-package'
    runs-on: self-hosted
    steps:
      - name: Upgrade Package
        working-directory: scripts
        run: |
            echo "Upgrading Docker,GIT and TRIVY"
            whoami
            sudo chmod +x install-update.sh
            sudo ./install-update.sh
  spawn-container:
    if: github.event.inputs.environment == 'spawn-container'
    runs-on: self-hosted
    steps:
      - name: Spawn Container
        working-directory: scripts
        run: |
            echo "Creating containers"
            whoami
            sudo chmod +x spawn_container.sh
            sudo ./spawn_container.sh
  delete-container:
    if: github.event.inputs.environment == 'delete-container'
    runs-on: self-hosted
    steps:
      - name: Delete Container
        working-directory: scripts
        run: |
            echo "Deleting containers"
            whoami
            sudo chmod +x kill.sh
            sudo ./kill.sh

  scan-images:
    if: github.event.inputs.environment == 'scan-images'
    runs-on: self-hosted
    steps:
        - name: Create directory for scan images
          run: |
              sudo mkdir -p /home/ec2-user/scan-images
              sudo ls -al /home/ec2-user/
              sudo chmod -R +777 /home/ec2-user/scan-images
  
        - name: Scan Database Docker images
          run: |
              sudo trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/todo-database:stable > /home/ec2-user/scan-images/database_scan-$(git rev-parse HEAD)-$(date +'%Y-%m-%d_%H-%M').txt
  
        - name: Scan Backend Docker images
          run: |
              sudo trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/todo-backend:stable > /home/ec2-user/scan-images/backend_scan-$(git rev-parse HEAD)-$(date +'%Y-%m-%d_%H-%M').txt
  
        - name: Scan Frontend Docker images
          run: |
              sudo trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/todo-frontend:stable > /home/ec2-user/scan-images/frontend_scan-$(git rev-parse HEAD)-$(date +'%Y-%m-%d_%H-%M').txt
  
        - name: listing scanned results
          run: |
              ls -al /home/ec2-user/scan-images

  push-images:
    if: github.event.inputs.environment == 'push-images'
    runs-on: self-hosted
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Login to Docker Hub
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
        - name: Push Database Docker images
          run: |
            sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-database:stable
            sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-database:$(git rev-parse HEAD)
        
        - name: Push Backend Docker images
          run: |
            sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:stable
            sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:$(git rev-parse HEAD)
        
        - name: Push Frontend Docker images
          run: |
            sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:stable
            sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:$(git rev-parse HEAD)
        
        - name: Logout from Docker Hub
          run: docker logout
  
