name: Docker Build 3-tier image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_images:
    runs-on: self-hosted

    needs: [build_database, build_backend, build_frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push Database Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-database:stable
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-database:$(git rev-parse HEAD)

    - name: Push Backend Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:stable
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:$(git rev-parse HEAD)

    - name: Push Frontend Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:stable
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:$(git rev-parse HEAD)

    - name: Logout from Docker Hub
      run: docker logout
